services:

  web:
    build:
      context: .
    ports:
      - 8080:5000
    secrets:
      - db-password
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    expose:
      - 3306
      - 33060

secrets:
  db-password:
    file: db-password.txt
